### ISSUE TITLE
GPU memory increasing, then eventually OOM

### ISSUE THREAD

**Issue by DangChuong-DC** [open-mmlab/mmrotate#43]
I tried to run Rotated-Faster-RCNN on dota-1.5 dataset. 
I found that GPU memory is increasing throughout the training and eventually OOM.
Below image is my run with 1 GPU.

**Image**
![Screenshot from 2022-02-28 22-32-12](https://user-images.githubusercontent.com/40515271/155991841-c348eb71-e865-4951-8867-3058eec281c1.png)

**Comment by yangxue0827** [comment]
Please run python mmrotate/utils/collect_env.py to collect necessary environment information and paste it here.

**Comment by yangxue0827** [comment]
Also, please provide your configs in the path of work_dirs.

**Comment by williamcorsel** [comment]
Experienced the same issue with Oriented R-CNN. I fixed it by setting the `gpu_assign_thr` flag following the suggestion [here](https://github.com/open-mmlab/mmrotate/blob/7c9a592fdda583f3b6c0d200c14020daca18317b/docs/en/faq.md?plain=1#L72)

**Comment by DangChuong-DC** [comment]
Thank you @yangxue0827 for prompt response and your dedicated works.
@williamcorsel I confirmed that setting `gpu_assign_thr=100` resolved my issues.

Great works, thank you very much.
